[www]
pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 5
pm.max_requests = 500

; Pass environment variables from Docker to PHP workers
clear_env = no

; Catch stdout/stderr from workers
catch_workers_output = yes
php_admin_flag[log_errors] = on
